# Antigravity Automation Script
# Generated by Gemini CLI

$AG_PATH = "C:\Users\Genaro Aurelio\AppData\Local\Programs\Antigravity\bin\antigravity.cmd"

function ag {
    & $AG_PATH $args
}

function subir {
    param(
        [string]$message = "Auto-update: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    )
    
    if (!(Test-Path .git)) {
        Write-Host "Git repository not found. Initializing..." -ForegroundColor Yellow
        git init
        gh repo create (Split-Path -Leaf (Get-Location)) --public --source=. --remote=origin --push
    }
    
    git add .
    git commit -m $message
    git push
}

function ag-build {
    if (Test-Path *.csproj) {
        dotnet build
    } elseif (Test-Path package.json) {
        npm run build
    } else {
        Write-Host "No known project structure found." -ForegroundColor Red
    }
}

function ag-status {
    Write-Host "--- Antigravity Status ---" -ForegroundColor Cyan
    Write-Host "Antigravity CLI: $(if (Test-Path $AG_PATH) { 'OK' } else { 'Missing' })"
    Write-Host "Git: $(if (Get-Command git -ErrorAction SilentlyContinue) { 'OK' } else { 'Missing' })"
    Write-Host "Dotnet: $(if (Get-Command dotnet -ErrorAction SilentlyContinue) { 'OK' } else { 'Missing' })"
    Write-Host "--------------------------"
}

# Export aliases
Set-Alias -Name ag -Value ag
Set-Alias -Name subir -Value subir
Set-Alias -Name build -Value ag-build
Set-Alias -Name status -Value ag-status

function save {
    param([string]$msg = "Guardado manual")
    if (Test-Path ".\checkpoint.ps1") {
        . .\checkpoint.ps1
        New-Checkpoint -Message $msg
    } else {
        Write-Host "âš ï¸  Archivo checkpoint.ps1 no encontrado." -ForegroundColor Red
    }
}
